### ISSUE TITLE
SearchableDropdown not working in Firefox and Safari on Mac

### ISSUE THREAD

**Issue by grynag** [equinor/fusion-components#536] opened 2020-05-07 06:33 UTC
When selecting an item in the searchable dropdown the dropdown closes, but no option is selected. 

**Tested in** 
_Firefox:_ 
- Developer Edition version 77.0b2 a
- Firefox version 76.0. 

_Safari:_ 
- Version 13.1.

**Comment by EskilSaatvedt** [comment] 2020-05-29 06:21
We found more locations where this is an issue.

**Comment by odinr** [comment] 2020-06-29 13:14
This issue should be resolved in v1.1.96

The issue was caused by blur event as triggered before click, which unmounted component before handling selection.

@see #626

**Closed by odinr** 2020-06-29 13:14 UTC
